version: '3'
services:
  frontend:
    build: ./frontend
    ports: ["3000:3000"]

  backend:
    build: ./backend
    ports: ["5000:5000"]

  model:
    build: ./model
    ports: ["8000:8000"]


   // bat 'docker-compose up -d --build'
